# .travis.yml
language: ruby
rvm:
  - 1.9.3
    env:
      - DB=mysql
before_script:
  - mysql -e 'create database rails_test ;'
  - mysql -e 'CREATE USER 'rails'@'%' IDENTIFIED BY 'rails';'
  - mysql -e 'GRANT ALL PRIVILEGES ON *.* TO 'rails'@'%' WITH GRANT OPTION;'

