defaults: &defaults
  jmeter_bin_path: "bin/jmeter.sh"
  jmeter_theads: 4
  jmeter_jtl_path: "reports/"
  jmeter_jmx_path: "/definition_files"
  jmeter_log: "log/jmeter.log"
  jmeter_script: false
  svn_user: 'xgujsvn'
  svn_passwd: 'baumwall'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
