--- 
address: 0.0.0.0
pid: tmp/pids/thin.pid
port: 80
wait: 30
timeout: 30
log: log/thin.log
max_conns: 1024
require: []

max_persistent_conns: 512
environment: development
servers: 2
daemonize: true
chdir: /app1/jmeter/site
